spring:
  application:
    name: flowk-back
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flowk


minio:
  endpoint: "http://localhost:9002"
  access-key: "minioadmin"
  secret-key: "minioadmin"
  bucket-name: models